version: '3.8'

name: soshell
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: prompt-catalog
    ports:
      - 3000:3000
    environment:
      - POSTGRES_DB=soshell
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
    networks:
      - soshell_net
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: soshell
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - soshell_net

  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://postgres:5432/soshell -user=user -password=password migrate
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - postgres
    networks:
      - soshell_net

volumes:
  postgres_data:

networks:
  soshell_net: